# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tesser.rpc.v1 import tesser_pb2 as tesser_dot_rpc_dot_v1_dot_tesser__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tesser/rpc/v1/tesser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/tesser.rpc.v1.StrategyService/Initialize',
                request_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.InitRequest.SerializeToString,
                response_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/tesser.rpc.v1.StrategyService/Heartbeat',
                request_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.OnTick = channel.unary_unary(
                '/tesser.rpc.v1.StrategyService/OnTick',
                request_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.TickRequest.SerializeToString,
                response_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
                _registered_method=True)
        self.OnCandle = channel.unary_unary(
                '/tesser.rpc.v1.StrategyService/OnCandle',
                request_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.CandleRequest.SerializeToString,
                response_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
                _registered_method=True)
        self.OnOrderBook = channel.unary_unary(
                '/tesser.rpc.v1.StrategyService/OnOrderBook',
                request_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.OrderBookRequest.SerializeToString,
                response_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
                _registered_method=True)
        self.OnFill = channel.unary_unary(
                '/tesser.rpc.v1.StrategyService/OnFill',
                request_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.FillRequest.SerializeToString,
                response_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnCandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnFill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.InitRequest.FromString,
                    response_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.InitResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.HeartbeatRequest.FromString,
                    response_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.HeartbeatResponse.SerializeToString,
            ),
            'OnTick': grpc.unary_unary_rpc_method_handler(
                    servicer.OnTick,
                    request_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.TickRequest.FromString,
                    response_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.SerializeToString,
            ),
            'OnCandle': grpc.unary_unary_rpc_method_handler(
                    servicer.OnCandle,
                    request_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.CandleRequest.FromString,
                    response_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.SerializeToString,
            ),
            'OnOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.OnOrderBook,
                    request_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.OrderBookRequest.FromString,
                    response_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.SerializeToString,
            ),
            'OnFill': grpc.unary_unary_rpc_method_handler(
                    servicer.OnFill,
                    request_deserializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.FillRequest.FromString,
                    response_serializer=tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tesser.rpc.v1.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tesser.rpc.v1.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tesser.rpc.v1.StrategyService/Initialize',
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.InitRequest.SerializeToString,
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tesser.rpc.v1.StrategyService/Heartbeat',
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.HeartbeatRequest.SerializeToString,
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tesser.rpc.v1.StrategyService/OnTick',
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.TickRequest.SerializeToString,
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnCandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tesser.rpc.v1.StrategyService/OnCandle',
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.CandleRequest.SerializeToString,
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tesser.rpc.v1.StrategyService/OnOrderBook',
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.OrderBookRequest.SerializeToString,
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnFill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tesser.rpc.v1.StrategyService/OnFill',
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.FillRequest.SerializeToString,
            tesser_dot_rpc_dot_v1_dot_tesser__pb2.SignalList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
